name: Epiviz Help Pages
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
pygments: true
baseurl:
epivizUiMain: http://epiviz-dev.cbcb.umd.edu/v2/ui/
epivizDataMain: http://epiviz-dev.cbcb.umd.edu/v2/data/
