name: Epiviz Help Pages
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
pygments: true
baseurl:
epivizUiMain: http://epiviz.cbcb.umd.edu/
epivizDataMain: http://epiviz.cbcb.umd.edu/data/
pageOrder: ["/index.html", "/charts.html", "/computed-measurements.html", "/dataprovider-plugins.html", "/epivizr.html", "/plugins.html", "/websocket.html"]
